# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\x12\x05\x63\x61\x63he\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10HeartbeatRequest\"$\n\x11HeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\x13RegisterNodeRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\'\n\x14RegisterNodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0fGetNodesRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"%\n\x10GetNodesResponse\x12\x11\n\taddresses\x18\x01 \x03(\t2\xe1\x01\n\x0c\x43\x61\x63heService\x12,\n\x03Get\x12\x11.cache.GetRequest\x1a\x12.cache.GetResponse\x12,\n\x03Set\x12\x11.cache.SetRequest\x1a\x12.cache.SetResponse\x12\x35\n\x06\x44\x65lete\x12\x14.cache.DeleteRequest\x1a\x15.cache.DeleteResponse\x12>\n\tHeartbeat\x12\x17.cache.HeartbeatRequest\x1a\x18.cache.HeartbeatResponse2\x9a\x01\n\x12\x43oordinatorService\x12G\n\x0cRegisterNode\x12\x1a.cache.RegisterNodeRequest\x1a\x1b.cache.RegisterNodeResponse\x12;\n\x08GetNodes\x12\x16.cache.GetNodesRequest\x1a\x17.cache.GetNodesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=22
  _globals['_GETREQUEST']._serialized_end=47
  _globals['_GETRESPONSE']._serialized_start=49
  _globals['_GETRESPONSE']._serialized_end=92
  _globals['_SETREQUEST']._serialized_start=94
  _globals['_SETREQUEST']._serialized_end=134
  _globals['_SETRESPONSE']._serialized_start=136
  _globals['_SETRESPONSE']._serialized_end=166
  _globals['_DELETEREQUEST']._serialized_start=168
  _globals['_DELETEREQUEST']._serialized_end=196
  _globals['_DELETERESPONSE']._serialized_start=198
  _globals['_DELETERESPONSE']._serialized_end=231
  _globals['_HEARTBEATREQUEST']._serialized_start=233
  _globals['_HEARTBEATREQUEST']._serialized_end=251
  _globals['_HEARTBEATRESPONSE']._serialized_start=253
  _globals['_HEARTBEATRESPONSE']._serialized_end=289
  _globals['_REGISTERNODEREQUEST']._serialized_start=291
  _globals['_REGISTERNODEREQUEST']._serialized_end=329
  _globals['_REGISTERNODERESPONSE']._serialized_start=331
  _globals['_REGISTERNODERESPONSE']._serialized_end=370
  _globals['_GETNODESREQUEST']._serialized_start=372
  _globals['_GETNODESREQUEST']._serialized_end=402
  _globals['_GETNODESRESPONSE']._serialized_start=404
  _globals['_GETNODESRESPONSE']._serialized_end=441
  _globals['_CACHESERVICE']._serialized_start=444
  _globals['_CACHESERVICE']._serialized_end=669
  _globals['_COORDINATORSERVICE']._serialized_start=672
  _globals['_COORDINATORSERVICE']._serialized_end=826
# @@protoc_insertion_point(module_scope)
